version: 2
jobs:
  build:

    docker:
      - image: oracle/graalvm-ce:1.0.0-rc9

    steps:
      - checkout

      - restore_cache:
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Install Apache Maven
          command: |
            yum install -y wget
            wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
            yum install -y apache-maven
            mvn -version

      - run:
          name: Run tests
          command: |
            mvn clean verify

      - save_cache:
          paths:
            - ~/.m2
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - store_test_results:
          path: "target/surefire-reports/"

      - store_test_results:
          path: "target/failsafe-reports/"